// <auto-generated />
using System;
using HeQuanTriDB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeQuanTriDB.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20250324210711_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeQuanTriDB.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("MaChiTietHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietHoaDon"));

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("MaMonAn")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<double>("ThanhTien")
                        .HasColumnType("float");

                    b.HasKey("MaChiTietHoaDon");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaMonAn");

                    b.ToTable("ChiTietHoaDons");
                });

            modelBuilder.Entity("HeQuanTriDB.Models.ChucVu", b =>
                {
                    b.Property<int>("MaChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChucVu"));

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaChucVu");

                    b.ToTable("ChucVus");
                });

            modelBuilder.Entity("HeQuanTriDB.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<double>("TongTien")
                        .HasColumnType("float");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("HeQuanTriDB.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKhachHang");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("HeQuanTriDB.Models.KhuyenMai", b =>
                {
                    b.Property<int>("MaKhuyenMai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhuyenMai"));

                    b.Property<bool>("DaDung")
                        .HasColumnType("bit");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKhuyenMai");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("KhuyenMais");
                });

            modelBuilder.Entity("HeQuanTriDB.Models.LuuTru", b =>
                {
                    b.Property<int>("MaLuuTru")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLuuTru"));

                    b.Property<int>("MaNguyenLieu")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaLuuTru");

                    b.HasIndex("MaNguyenLieu");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("LuuTrus");
                });

            modelBuilder.Entity("HeQuanTriDB.Models.MonAn", b =>
                {
                    b.Property<int>("MaMonAn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMonAn"));

                    b.Property<double>("Gia")
                        .HasColumnType("float");

                    b.Property<int>("SoLuongHienCo")
                        .HasColumnType("int");

                    b.Property<string>("TenMonAn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaMonAn");

                    b.ToTable("MonAns");
                });

            modelBuilder.Entity("HeQuanTriDB.Models.NguyenLieu", b =>
                {
                    b.Property<int>("MaNguyenLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguyenLieu"));

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("Gia")
                        .HasColumnType("float");

                    b.Property<int>("MaNhaCungCap")
                        .HasColumnType("int");

                    b.Property<string>("TenNguyenLieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNguyenLieu");

                    b.HasIndex("MaNhaCungCap");

                    b.ToTable("NguyenLieus");
                });

            modelBuilder.Entity("HeQuanTriDB.Models.NhaCungCap", b =>
                {
                    b.Property<int>("MaNhaCungCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhaCungCap"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNhaCungCap");

                    b.ToTable("NhaCungCaps");
                });

            modelBuilder.Entity("HeQuanTriDB.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaChucVu")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("MaChucVu");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("HeQuanTriDB.Models.NhapKho", b =>
                {
                    b.Property<int>("MaNhapKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhapKho"));

                    b.Property<int>("MaNguyenLieu")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("SoNgayHetHan")
                        .HasColumnType("int");

                    b.Property<double>("TongTien")
                        .HasColumnType("float");

                    b.HasKey("MaNhapKho");

                    b.HasIndex("MaNguyenLieu");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("NhapKhos");
                });

            modelBuilder.Entity("HeQuanTriDB.Models.XuatKho", b =>
                {
                    b.Property<int>("MaXuatKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaXuatKho"));

                    b.Property<int>("MaLuuTru")
                        .HasColumnType("int");

                    b.Property<int>("MaNguyenLieu")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayXuat")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguyenNhanXuatKho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaXuatKho");

                    b.HasIndex("MaLuuTru");

                    b.HasIndex("MaNguyenLieu");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("XuatKhos");
                });

            modelBuilder.Entity("HeQuanTriDB.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("HeQuanTriDB.Models.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HeQuanTriDB.Models.MonAn", "MonAn")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaMonAn")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("HeQuanTriDB.Models.HoaDon", b =>
                {
                    b.HasOne("HeQuanTriDB.Models.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HeQuanTriDB.Models.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HeQuanTriDB.Models.KhuyenMai", b =>
                {
                    b.HasOne("HeQuanTriDB.Models.KhachHang", "KhachHang")
                        .WithMany("KhuyenMais")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("HeQuanTriDB.Models.LuuTru", b =>
                {
                    b.HasOne("HeQuanTriDB.Models.NguyenLieu", "NguyenLieu")
                        .WithMany("LuuTrus")
                        .HasForeignKey("MaNguyenLieu")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HeQuanTriDB.Models.NhanVien", "NhanVien")
                        .WithMany("LuuTrus")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NguyenLieu");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HeQuanTriDB.Models.NguyenLieu", b =>
                {
                    b.HasOne("HeQuanTriDB.Models.NhaCungCap", "NhaCungCap")
                        .WithMany("NguyenLieus")
                        .HasForeignKey("MaNhaCungCap")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("HeQuanTriDB.Models.NhanVien", b =>
                {
                    b.HasOne("HeQuanTriDB.Models.ChucVu", "ChucVu")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaChucVu")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChucVu");
                });

            modelBuilder.Entity("HeQuanTriDB.Models.NhapKho", b =>
                {
                    b.HasOne("HeQuanTriDB.Models.NguyenLieu", "NguyenLieu")
                        .WithMany("NhapKhos")
                        .HasForeignKey("MaNguyenLieu")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HeQuanTriDB.Models.NhanVien", "NhanVien")
                        .WithMany("NhapKhos")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NguyenLieu");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HeQuanTriDB.Models.XuatKho", b =>
                {
                    b.HasOne("HeQuanTriDB.Models.LuuTru", "LuuTru")
                        .WithMany("XuatKhos")
                        .HasForeignKey("MaLuuTru")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HeQuanTriDB.Models.NguyenLieu", "NguyenLieu")
                        .WithMany("XuatKhos")
                        .HasForeignKey("MaNguyenLieu")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HeQuanTriDB.Models.NhanVien", "NhanVien")
                        .WithMany("XuatKhos")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LuuTru");

                    b.Navigation("NguyenLieu");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HeQuanTriDB.Models.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("HeQuanTriDB.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("HeQuanTriDB.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("KhuyenMais");
                });

            modelBuilder.Entity("HeQuanTriDB.Models.LuuTru", b =>
                {
                    b.Navigation("XuatKhos");
                });

            modelBuilder.Entity("HeQuanTriDB.Models.MonAn", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("HeQuanTriDB.Models.NguyenLieu", b =>
                {
                    b.Navigation("LuuTrus");

                    b.Navigation("NhapKhos");

                    b.Navigation("XuatKhos");
                });

            modelBuilder.Entity("HeQuanTriDB.Models.NhaCungCap", b =>
                {
                    b.Navigation("NguyenLieus");
                });

            modelBuilder.Entity("HeQuanTriDB.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("LuuTrus");

                    b.Navigation("NhapKhos");

                    b.Navigation("XuatKhos");
                });
#pragma warning restore 612, 618
        }
    }
}
